# Generated by Django 4.2.1 on 2023-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Unknown', max_length=255)),
                ('password', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='username',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(default='Unknown', max_length=46),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
