# Generated by Django 4.2.1 on 2023-06-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs_app', '0002_user_file_username_alter_file_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uc_tokens',
            field=models.IntegerField(default=100),
        ),
    ]
