# Generated by Django 4.2.1 on 2023-06-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs_app', '0003_user_uc_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='peer_id',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
