# Generated by Django 4.2.1 on 2023-06-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs_app', '0004_user_peer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uc_tokens',
            field=models.FloatField(default=100),
        ),
    ]
